### ISSUE TITLE
Unhandled PipelineStoppedException

### ISSUE THREAD

**Issue by DanAtkinson** [wgross/fswatcher-engine-event#7]
Hi there,

I have a watch on a .NET bin directory to copy the contents to a different directory whenever I compile my application:

```powershell
$FileTypes = "*.dll *.pdb *.xml *.config"
$SourceDirectory = "D:\path\to\A\bin\"
$SourceDirectoryHash = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($SourceDirectory ))
$DestinationDirectory = "D:\path\to\B\bin\"
$DestinationDirectoryHash = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($DestinationDirectory))
$FileTypesHash = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($FileTypes))
$SourceIdentifier = "WatchFolder###$($SourceDirectoryHash)###$($DestinationDirectoryHash)###$($FileTypesHash)"

robocopy "$($SourceDirectory )" "$($DestinationDirectory)" $FileTypes /E

$FileSystemWatcher = New-FileSystemWatcher -SourceIdentifier $SourceIdentifier -Path "$($SourceDirectory )" -IncludeSubdirectories -Action {
	# Because the SourceDirectory and DestinationDirectory are not available in this context, I've embedded them in the SourceIdentifier to be split out when a change is detected.
        #! I'd appreciate any advice on a better way of doing this!
	$SourceIdentifiers = $Event.SourceIdentifier.Split("###")
	$SourceDirectory = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($SourceIdentifiers[1]))
	$DestinationDirectory = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($SourceIdentifiers[2]))
	$FileTypes = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($SourceIdentifiers[3]))
	$ChangedPath = $Event.MessageData.FullPath.Replace($SourceDirectory, "")
	Write-Host 
	Write-Host "Change detected at $(Get-Date -Format 'dd MMMM yyyy HH:mm:ss:fff')" -ForegroundColor White
	Write-Host "Source: $($SourceDirectory)" -ForegroundColor Yellow
	Write-Host "Path: '$($ChangedPath)'" -ForegroundColor Yellow
	robocopy "$($SourceDirectory)" "$($DestinationDirectory)" $FileTypes /E
}
```

Unfortunately, on several occasions, this has resulted in an unhandled exception occurring:

```
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception.
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord errorRecord, Nullable`1 actionPreference, Boolean isFromNativeStdError)
   at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord, Boolean overrideInquire)
   at FSWatcherEngineEvent.FileSystemWatcherSubscription.OnError(Object sender, ErrorEventArgs e) in D:\src\fswatcher-engine-event\src\FSWatcherEngineEvent\FileSystemWatcherSubscription.cs:line 54
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__85_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord errorRecord, Nullable`1 actionPreference, Boolean isFromNativeStdError)
   at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord, Boolean overrideInquire)
   at FSWatcherEngineEvent.FileSystemWatcherSubscription.OnError(Object sender, ErrorEventArgs e) in D:\src\fswatcher-engine-event\src\FSWatcherEngineEvent\FileSystemWatcherSubscription.cs:line 54
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__85_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Any advice on this would be greatly appreciated. On the face of it, the robocopy script is probably excessive and annoyingly the same file changes keep triggering a brand new robocopy. For example:

```
Change detected at 10 February 2023 11:22:15:268
Source: D:\path\to\A\bin\
Path: 'System.IO.Pipelines.dll'

Change detected at 10 February 2023 11:22:15:653
Source: D:\path\to\A\bin\
Path: 'System.IO.Pipelines.dll'

Change detected at 10 February 2023 11:22:16:355
Source: D:\path\to\A\bin\
Path: 'System.IO.Pipelines.dll'
```

**Comment by wgross** [comment]
Hmm interesting. 
Do you use Powershell 7 or 5?

Without having experimented with this I would assume that the copy operation takes some time and creates backpresssure in powershell messaging pipeline.

Do you experience the same problem if you don't physically copy the files? This would identify duration of the robocopy execution as the origin of the problem. A possible workaround fot this could be to suspend the watcher before copying and resuming later but i don't know if this happens enough.

Another way to avoid backpressure would be to decouple copying and watching. Let the watch script write a timestamp to a file somewhere and start the copying in a bg job which processes a loop:
- read the file with the timestamp, 
- if the file stamp is different from previous one copy the directory
- sleep some seconds
- repeat

In addition I will create a test scenario similar to reproduce this during the next days....

**Comment by wgross** [comment]
In addition: are you  sure none of the script lines before the robocopy raises an exception? you may want to enforce this with a  try {} catch {}  around the script, just to soothe that feeling of paranoia (of mine) :-)

**Comment by DanAtkinson** [comment]
> Do you use Powershell 7 or 5?

My current version is PowerShell 7.3.2 - from the main repo - https://github.com/PowerShell/PowerShell/.

> Do you experience the same problem if you don't physically copy the files? 

No. Never. Before using FSWatcher, I used the same robocopy script, but with /MON:1. However, waiting a minute was getting a bit silly, and I'd often stop the job and restart it. That's why I switched to this.

> Another way to avoid backpressure would be to decouple copying and watching.

I have considered this as well. Stamping a change and sleeping, but the reason I switched to FSWatcher is that 1 minute was too long, and ideally I'd like to wait no more than 5 seconds. I feel like I'd be no better off than I was before.

Another alternative is that I'm more granular in the robocopy, and just copy the file using the `$ChangedPath`.

> In addition: are you sure none of the script lines before the robocopy raises an exception?

They are not. The previous lines were similar "Change detected at..." that I've been outputting 

> you may want to enforce this with a try {} catch {} around the script, just to soothe that feeling of paranoia (of mine) :-)

I will do this.

**Comment by wgross** [comment]
> > Do you experience the same problem if you don't physically copy the files?
> 
> No. Never. Before using FSWatcher, I used the same robocopy script, but with /MON:1. However, waiting a minute was getting a bit silly, and I'd often stop the job and restart it. That's why I switched to this.

I see. 
Since the 'processing' end of the pipeline is from powershell I don't believe I can do much to improve its robustness. The only solution that comes to my mind is to provide an option at FSWatcher to not use the powershell pipeline at all and execute the handler scriptblock directly. This would mean that FSWatcher still manages the .NET FSWatcher instance which is comfortable but doesn't allow to hook into a source identifier with different/replacable action handlers.

**Comment by wgross** [comment]
Reproduced it: It happens when the watched directory is deleted. 
This seems to cause an access violation. I don't know yet if i can recover from this in  the FSWatcher with some clever trick like re-create the watcher...

**Comment by wgross** [comment]
I haven't found a way to this exception neither can I suppress it. I support 'not deleting the watched directory' is the best solution for this. :-/

**Comment by DanAtkinson** [comment]
Thanks. In that case I'm unable to use fswatcher for .NET where the bin directory is deleted as part of the build process.

As I'm trying to keep a single job to maintain different directories, I'm going to reimplement the solution with a watcher on the parent to recycle the watcher if it detects the target directory has been deleted. This should raise a FileSystemWatcher.Error for me to handle and action appropriately.

Kind regards
Dan
